language: generic
# config property

# need super user permissions to run this build
sudo: required

# next must have docker
services:
  - docker

# a series of steps before the project tests run (use Dockerfile)
before_install:
  - docker build -t bryjos44/docker-testing -f Dockerfile.dev .

# all the different commands needed to run a test suite
script:
  - docker run -e CI=true bryjos44/docker-testing npm run test

# config for AWS Elastic Beanstalk
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-116861327569"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY