version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes: 
      - /app/node_modules
      - .:/app
    stdin_open: true
    environment: 
      - CHOKIDAR_USEPOLLING=true
  react-tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    volumes: 
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]